"""
Hermite-like probe mode generation for multi-mode ptychography.

Line-by-line port of MATLAB +core/hermite_like.m from cSAXS PtychoShelves.

Creates orthonormalized Hermite-Gauss like basis functions from a
fundamental probe mode.  Higher-order modes are generated by multiplying
the fundamental with polynomial×Gaussian envelopes, then orthonormalized
via Gram-Schmidt.

Reference:
    P. Thibault and A. Menzel, "Reconstructing state mixtures from
    diffraction measurements," Nature 494, 68-71 (2013).
"""

import numpy as np


def hermite_like(fundam, X, Y, M, N):
    """
    Generate Hermite-like orthonormal probe modes.

    Port of MATLAB hermite_like.m.

    Parameters
    ----------
    fundam : ndarray (Ny, Nx), complex
        Fundamental probe mode (mode 0).
    X : ndarray (Ny, Nx)
        Horizontal coordinate grid (meshgrid output).
    Y : ndarray (Ny, Nx)
        Vertical coordinate grid (meshgrid output).
    M : int
        Maximum order in x direction.
    N : int
        Maximum order in y direction.

    Returns
    -------
    H : ndarray (Ny, Nx, num_modes)
        Orthonormalized Hermite-like modes.
        H[:,:,0] = normalized fundamental.
        Total number of modes = (M+1)*(N+1).
    """
    m_range = np.arange(M + 1)   # hermite_like.m: m = [0:M]
    n_range = np.arange(N + 1)   # hermite_like.m: n = [0:N]

    abs_fundam2 = np.abs(fundam) ** 2
    total_intensity = np.sum(abs_fundam2)

    # Intensity-weighted centroid — hermite_like.m L73-74
    cenx = np.sum(X * abs_fundam2) / total_intensity
    ceny = np.sum(Y * abs_fundam2) / total_intensity

    # Intensity-weighted variance — hermite_like.m L75-76
    varx = np.sum((X - cenx) ** 2 * abs_fundam2) / total_intensity
    vary = np.sum((Y - ceny) ** 2 * abs_fundam2) / total_intensity

    Ny, Nx = fundam.shape
    num_modes = (M + 1) * (N + 1)
    H = np.zeros((Ny, Nx, num_modes), dtype=complex)

    counter = 0  # 0-based (MATLAB uses 1-based)

    # hermite_like.m L80-101: nested loop over (n, m) orders
    for nii in n_range:
        for mii in m_range:
            # Polynomial × fundamental — hermite_like.m L81
            auxfunc = ((X - cenx) ** mii) * ((Y - ceny) ** nii) * fundam

            if counter == 0:
                # First mode: just normalize — hermite_like.m L82-83
                norm_val = np.sqrt(np.sum(np.abs(auxfunc) ** 2))
                auxfunc = auxfunc / (norm_val + 1e-30)
            else:
                # Higher modes: apply Gaussian envelope — hermite_like.m L85-86
                gauss_env = np.exp(
                    -((X - cenx) ** 2 / (2 * varx))
                    - ((Y - ceny) ** 2 / (2 * vary))
                )
                auxfunc = auxfunc * gauss_env
                norm_val = np.sqrt(np.sum(np.abs(auxfunc) ** 2))
                auxfunc = auxfunc / (norm_val + 1e-30)

            # Gram-Schmidt orthogonalization — hermite_like.m L90-92
            for ii in range(counter):
                # MATLAB: sum(sum(H(:,:,ii).*conj(auxfunc),1),2)
                overlap = np.sum(H[:, :, ii] * np.conj(auxfunc))
                auxfunc = auxfunc - H[:, :, ii] * overlap

            # Re-normalize — hermite_like.m L93
            norm_val = np.sqrt(np.sum(np.abs(auxfunc) ** 2))
            auxfunc = auxfunc / (norm_val + 1e-30)

            H[:, :, counter] = auxfunc
            counter += 1

    return H
