"""compare_subpixel_vs_matlab.py

Rigorous comparison of Python find_shift_fast_2D port against MATLAB ground truth.

Strategy:
  1. Load matlab_subpixel_results.mat (generated by compare_subpixel_matlab.m)
  2. Run Python port on the EXACT same input arrays
  3. Compare Python vs MATLAB vs true shifts
  4. Report: MAE, max error, correlation, pass/fail per test case
  5. Generate visualisation: results/subpixel_comparison_vs_matlab.png

Usage:
    cd <PROJECTS_DIR>/K4GSR-TOMOGRAPHY/python_port
    python compare_subpixel_vs_matlab.py
"""

import sys, os
import numpy as np
import scipy.io as sio
import h5py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pathlib import Path

_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE))

from utils.find_shift_fast_2D import find_shift_fast_2D


def _load_mat73(path):
    """Load MATLAB v7.3 (.mat HDF5) file, returning a flat dict of numpy arrays."""
    out = {}
    def _vis(name, obj):
        if isinstance(obj, h5py.Dataset):
            val = obj[()]
            # HDF5 stores complex as struct with 'r' and 'i' fields
            if val.dtype.names and 'r' in val.dtype.names and 'i' in val.dtype.names:
                val = val['r'] + 1j * val['i']
            # Transpose: MATLAB stores column-major, HDF5 reads row-major
            # so h5py gives (N, ...) instead of (..., N) → need to transpose
            val = np.array(val).T if val.ndim > 1 else np.array(val).flatten()
            out[name] = val
    with h5py.File(path, 'r') as f:
        f.visititems(_vis)
    return out


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def _fix_axis_order(arr):
    """Convert MATLAB complex array to numpy complex.
    HDF5/h5py sometimes returns structured array with 'real'/'imag' fields."""
    arr = np.asarray(arr)
    if arr.dtype.names and 'real' in arr.dtype.names and 'imag' in arr.dtype.names:
        return arr['real'] + 1j * arr['imag']
    return arr.astype(complex)


def _report_test(name, true_shifts, matlab_shifts, python_shifts, tol_good=0.1, tol_ok=0.5):
    """Print formatted comparison table for one test."""
    true_shifts  = np.atleast_2d(true_shifts)
    matlab_shifts = np.atleast_2d(matlab_shifts)
    python_shifts = np.atleast_2d(python_shifts)

    n = true_shifts.shape[0]
    print(f"\n{'-'*72}")
    print(f"  {name}")
    print(f"{'-'*72}")
    hdr = f"  {'k':>3}  {'true_x':>8}  {'true_y':>8}  {'mat_x':>8}  {'mat_y':>8}  "
    hdr += f"{'py_x':>8}  {'py_y':>8}  {'e_mat':>7}  {'e_py':>7}  {'d_m-p':>9}"
    print(hdr)
    print(f"  {'-'*67}")

    err_mat  = []
    err_py   = []
    err_diff = []
    all_pass = True

    for k in range(n):
        tx, ty = true_shifts[k]
        mx, my = matlab_shifts[k]
        px, py = python_shifts[k]

        e_mat = np.sqrt((mx-tx)**2 + (my-ty)**2)
        e_py  = np.sqrt((px-tx)**2 + (py-ty)**2)
        e_diff = np.sqrt((px-mx)**2 + (py-my)**2)

        err_mat.append(e_mat);  err_py.append(e_py);  err_diff.append(e_diff)

        flag = 'OK' if e_py < tol_good else ('~' if e_py < tol_ok else 'FAIL')
        if e_py >= tol_ok:
            all_pass = False

        print(f"  {k+1:>3}  {tx:>8.3f}  {ty:>8.3f}  {mx:>8.3f}  {my:>8.3f}  "
              f"{px:>8.3f}  {py:>8.3f}  {e_mat:>7.4f}  {e_py:>7.4f}  {e_diff:>9.4f}  {flag}")

    err_mat  = np.array(err_mat)
    err_py   = np.array(err_py)
    err_diff = np.array(err_diff)

    print(f"\n  MATLAB  MAE={err_mat.mean():.4f}  max={err_mat.max():.4f}")
    print(f"  Python  MAE={err_py.mean():.4f}  max={err_py.max():.4f}")
    print(f"  Diff(Py-Mat) MAE={err_diff.mean():.4f}  max={err_diff.max():.4f}")
    print(f"  Status: {'ALL PASS' if all_pass else 'SOME FAIL'}")
    return err_mat, err_py, err_diff, all_pass


def apply_fourier_shift(blob, sx, sy):
    """Apply exact sub-pixel shift via Fourier phase ramp (matches MATLAB)."""
    Ny, Nx = blob.shape
    fy = np.fft.ifftshift(np.arange(-Ny//2, Ny//2) / Ny)
    fx = np.fft.ifftshift(np.arange(-Nx//2, Nx//2) / Nx)
    FX, FY = np.meshgrid(fx, fy)
    phase_ramp = np.exp(1j * 2 * np.pi * (sx * FX + sy * FY))
    shifted = np.fft.ifft2(np.fft.fft2(blob) * phase_ramp)
    return shifted.real.astype(complex)


# ──────────────────────────────────────────────────────────────────────────────
# Load MATLAB results
# ──────────────────────────────────────────────────────────────────────────────
mat_path = _HERE / 'results' / 'matlab_subpixel_results.mat'

if not mat_path.exists():
    print(f"ERROR: MATLAB result file not found: {mat_path}")
    print("Please run compare_subpixel_matlab.m first.")
    sys.exit(1)

print(f"Loading MATLAB results from:\n  {mat_path}")
mat = _load_mat73(str(mat_path))
print("Keys:", sorted(k for k in mat.keys()))

# ──────────────────────────────────────────────────────────────────────────────
# Extract arrays (MATLAB stores column-major, scipy.io.loadmat corrects this)
# ──────────────────────────────────────────────────────────────────────────────
blob_ref      = _fix_axis_order(mat['blob_ref'])        # (Ny, Nx)
true_shifts_A = np.array(mat['true_shifts_A'])          # (N_A, 2)
matlab_shifts_A = np.array(mat['matlab_shifts_A'])      # (N_A, 2)
stack1_A      = _fix_axis_order(mat['stack1_A'])        # (Ny, Nx, N_A)
stack2_A      = _fix_axis_order(mat['stack2_A'])        # (Ny, Nx, N_A)

true_shifts_B = np.array(mat['true_shifts_B'])
matlab_shifts_B = np.array(mat['matlab_shifts_B'])
stack1_B      = _fix_axis_order(mat['stack1'])          # var name in .mat is 'stack1'
stack2_B      = _fix_axis_order(mat['stack2'])

true_shifts_C = np.array(mat['true_shifts_C'])
matlab_shifts_C = np.array(mat['matlab_shifts_C'])
stack1_C      = _fix_axis_order(mat['stack1_C'])
stack2_C      = _fix_axis_order(mat['stack2_C'])

true_shifts_D = np.array(mat['true_shifts_D'])
matlab_shifts_D = np.array(mat['matlab_shifts_D'])
stack1_D      = _fix_axis_order(mat['stack1_D'])
stack2_D      = _fix_axis_order(mat['stack2_D'])

blob_shifted_E  = _fix_axis_order(mat['blob_shifted_E'])
shift_E_matlab  = np.array(mat['shift_E']).flatten()[:2]

blob_shifted_F  = _fix_axis_order(mat['blob_shifted_F_saved'])
sx_F = float(mat['sx_F'].flat[0])
sy_F = float(mat['sy_F'].flat[0])
shift_F_matlab  = np.array(mat['shift_F']).flatten()[:2]

print(f"\nArray shapes:")
print(f"  blob_ref={blob_ref.shape}, stack1_A={stack1_A.shape}, stack2_A={stack2_A.shape}")
print(f"  stack1_B={stack1_B.shape}, stack2_B={stack2_B.shape}")
print(f"  stack1_C={stack1_C.shape}, stack2_C={stack2_C.shape}")
print(f"  stack1_D={stack1_D.shape}, stack2_D={stack2_D.shape}")

# ──────────────────────────────────────────────────────────────────────────────
# Run Python find_shift_fast_2D on SAME inputs
# ──────────────────────────────────────────────────────────────────────────────
print("\n" + "="*72)
print("Running Python find_shift_fast_2D on MATLAB-generated inputs")
print("="*72)

# ---- Test A: 2D slice-by-slice (full_range) ----
# Python expects (Ny, Nx, N) for 3D input
py_shifts_A_list = []
for k in range(stack1_A.shape[2]):
    s = find_shift_fast_2D(stack1_A[:,:,k], stack2_A[:,:,k], sigma=0.01,
                           apply_fft=True, method='full_range')
    py_shifts_A_list.append(s)
python_shifts_A = np.array(py_shifts_A_list)

# ---- Test B: 3D stack ----
python_shifts_B = find_shift_fast_2D(stack1_B, stack2_B, sigma=0.01,
                                      apply_fft=True, method='full_range')

# ---- Test C: limited_range ----
py_shifts_C_list = []
for k in range(stack1_C.shape[2]):
    s = find_shift_fast_2D(stack1_C[:,:,k], stack2_C[:,:,k], sigma=0.01,
                           apply_fft=True, method='limited_range')
    py_shifts_C_list.append(s)
python_shifts_C = np.array(py_shifts_C_list)

# ---- Test D: pre-computed FFT ----
from scipy.signal.windows import tukey
Ny, Nx = blob_ref.shape
win_r = tukey(Ny, 0.5).reshape(-1, 1)
win_c = tukey(Nx, 0.5).reshape(1, -1)
sp_f = win_r * win_c

py_shifts_D_list = []
for k in range(stack1_D.shape[2]):
    o1f = np.fft.fft2(stack1_D[:,:,k] * sp_f)
    o2f = np.fft.fft2(stack2_D[:,:,k] * sp_f)
    s = find_shift_fast_2D(o1f, o2f, sigma=0.01, apply_fft=False, method='full_range')
    py_shifts_D_list.append(s)
python_shifts_D = np.array(py_shifts_D_list)

# ---- Test E: zero shift ----
shift_E_py = find_shift_fast_2D(blob_ref, blob_shifted_E, sigma=0.01,
                                  apply_fft=True, method='full_range')

# ---- Test F: sigma=0 ----
shift_F_py = find_shift_fast_2D(blob_ref, blob_shifted_F, sigma=0,
                                  apply_fft=True, method='full_range')

# ──────────────────────────────────────────────────────────────────────────────
# Report results
# ──────────────────────────────────────────────────────────────────────────────
print("\n" + "="*72)
print("COMPARISON RESULTS (Python vs MATLAB vs Ground Truth)")
print("="*72)

eA_m, eA_p, eA_d, pA = _report_test("Test A: 2D full_range (slice-by-slice)",
                                      true_shifts_A, matlab_shifts_A, python_shifts_A)
eB_m, eB_p, eB_d, pB = _report_test("Test B: 3D stack full_range",
                                      true_shifts_B, matlab_shifts_B, python_shifts_B)
eC_m, eC_p, eC_d, pC = _report_test("Test C: limited_range",
                                      true_shifts_C, matlab_shifts_C, python_shifts_C)
eD_m, eD_p, eD_d, pD = _report_test("Test D: pre-computed FFT (apply_fft=False)",
                                      true_shifts_D, matlab_shifts_D, python_shifts_D)

print(f"\n{'─'*72}")
print("  Test E: zero shift")
print(f"    MATLAB:  [{shift_E_matlab[0]:.4f}, {shift_E_matlab[1]:.4f}]")
print(f"    Python:  [{float(shift_E_py[0]):.4f}, {float(shift_E_py[1]):.4f}]  (expected ~[0,0])")
pass_E = float(np.max(np.abs(shift_E_py))) < 0.5
print(f"    Status: {'PASS' if pass_E else 'FAIL'}")

print(f"\n{'─'*72}")
print(f"  Test F: no spectral filter (sigma=0), true=[{sx_F:.1f}, {sy_F:.1f}]")
print(f"    MATLAB:  [{shift_F_matlab[0]:.4f}, {shift_F_matlab[1]:.4f}]")
print(f"    Python:  [{float(shift_F_py[0]):.4f}, {float(shift_F_py[1]):.4f}]")
e_F = float(np.max(np.abs(np.array([float(shift_F_py[0])-sx_F,
                                     float(shift_F_py[1])-sy_F]))))
pass_F = e_F < 0.5
print(f"    Python error: {e_F:.4f}  Status: {'PASS' if pass_F else 'FAIL'}")

# ──────────────────────────────────────────────────────────────────────────────
# Overall summary
# ──────────────────────────────────────────────────────────────────────────────
all_errs_py  = np.concatenate([eA_p, eB_p, eC_p, eD_p])
all_errs_mat = np.concatenate([eA_m, eB_m, eC_m, eD_m])
all_diffs    = np.concatenate([eA_d, eB_d, eC_d, eD_d])
all_pass = pA and pB and pC and pD and pass_E and pass_F

print(f"\n{'='*72}")
print("  OVERALL SUMMARY")
print(f"{'='*72}")
print(f"  MATLAB vs GT  MAE={all_errs_mat.mean():.4f}  max={all_errs_mat.max():.4f}")
print(f"  Python vs GT  MAE={all_errs_py.mean():.4f}  max={all_errs_py.max():.4f}")
print(f"  Py vs MATLAB  MAE={all_diffs.mean():.4f}  max={all_diffs.max():.4f}")
print(f"  Tests A-F:  {'ALL PASS' if all_pass else 'SOME FAIL'}")

# ──────────────────────────────────────────────────────────────────────────────
# Visualisation
# ──────────────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(15, 9))
fig.suptitle('Python vs MATLAB find_shift_fast_2D — Rigorous Comparison', fontsize=13)

def scatter_plot(ax, true_sh, mat_sh, py_sh, title, axis_label):
    t = true_sh[:, 0] if axis_label == 'x' else true_sh[:, 1]
    m = mat_sh[:, 0]  if axis_label == 'x' else mat_sh[:, 1]
    p = py_sh[:, 0]   if axis_label == 'x' else py_sh[:, 1]
    ax.scatter(t, m, c='steelblue', s=60, label='MATLAB', zorder=3)
    ax.scatter(t, p, c='tomato',    s=60, marker='^', label='Python', zorder=4)
    lim = max(abs(t).max(), 1.5) * 1.2
    ax.plot([-lim, lim], [-lim, lim], 'k--', lw=0.8, alpha=0.5)
    ax.set_xlabel(f'True shift ({axis_label})')
    ax.set_ylabel(f'Estimated shift ({axis_label})')
    ax.set_title(title)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

scatter_plot(axes[0,0], true_shifts_A, matlab_shifts_A, python_shifts_A, 'Test A: full_range (x)', 'x')
scatter_plot(axes[0,1], true_shifts_A, matlab_shifts_A, python_shifts_A, 'Test A: full_range (y)', 'y')
scatter_plot(axes[0,2], true_shifts_B, matlab_shifts_B, python_shifts_B, 'Test B: 3D stack (x)', 'x')
scatter_plot(axes[1,0], true_shifts_C, matlab_shifts_C, python_shifts_C, 'Test C: limited_range (x)', 'x')
scatter_plot(axes[1,1], true_shifts_D, matlab_shifts_D, python_shifts_D, 'Test D: pre-FFT (x)', 'x')

# Error comparison bar chart
ax = axes[1,2]
tests = ['A\nfull', 'B\n3D', 'C\nlim', 'D\npre-FFT']
mae_mat = [eA_m.mean(), eB_m.mean(), eC_m.mean(), eD_m.mean()]
mae_py  = [eA_p.mean(), eB_p.mean(), eC_p.mean(), eD_p.mean()]
x = np.arange(len(tests))
ax.bar(x - 0.2, mae_mat, 0.35, label='MATLAB', color='steelblue', alpha=0.8)
ax.bar(x + 0.2, mae_py,  0.35, label='Python', color='tomato',    alpha=0.8)
ax.set_xticks(x); ax.set_xticklabels(tests)
ax.set_ylabel('MAE (pixels)')
ax.set_title('MAE: Python vs MATLAB')
ax.legend(fontsize=8)
ax.grid(True, alpha=0.3, axis='y')
ax.axhline(0.1, color='green', lw=1.2, ls='--', label='0.1 px threshold', alpha=0.7)

plt.tight_layout()
out_path = _HERE / 'results' / 'subpixel_comparison_vs_matlab.png'
plt.savefig(str(out_path), dpi=120, bbox_inches='tight')
print(f"\nFigure saved: {out_path}")

# ──────────────────────────────────────────────────────────────────────────────
# Save numerical comparison as .npz for record
# ──────────────────────────────────────────────────────────────────────────────
npz_path = _HERE / 'results' / 'subpixel_comparison_vs_matlab.npz'
np.savez(str(npz_path),
         true_shifts_A=true_shifts_A, matlab_shifts_A=matlab_shifts_A, python_shifts_A=python_shifts_A,
         true_shifts_B=true_shifts_B, matlab_shifts_B=matlab_shifts_B, python_shifts_B=python_shifts_B,
         true_shifts_C=true_shifts_C, matlab_shifts_C=matlab_shifts_C, python_shifts_C=python_shifts_C,
         true_shifts_D=true_shifts_D, matlab_shifts_D=matlab_shifts_D, python_shifts_D=python_shifts_D)
print(f"Numerical results saved: {npz_path}")

sys.exit(0 if all_pass else 1)
