#!/bin/bash
# =============================================================
#  K4GSR BL10 NanoProbe -- Linux Production Server Setup
#  Target: Ubuntu 22.04 LTS
#
#  Usage:
#    sudo bash deploy/setup_production.sh [--config /path/to/config.env]
#
#  All settings are read from deploy/config.env (no hardcoded values).
#  Edit config.env before running to change paths, users, ports, etc.
# =============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ---- Load configuration ----
CONFIG_FILE="$SCRIPT_DIR/config.env"
if [ "${1:-}" = "--config" ] && [ -n "${2:-}" ]; then
    CONFIG_FILE="$2"
    shift 2
fi

if [ ! -f "$CONFIG_FILE" ]; then
    echo "[ERROR] Config file not found: $CONFIG_FILE"
    echo "  Create deploy/config.env first (see deploy/config.env in repo)."
    exit 1
fi

# shellcheck source=config.env
source "$CONFIG_FILE"

# ---- Derived variables ----
PY_CMD="python${PYTHON_VERSION}"
VENV_DIR="${INSTALL_DIR}/.venv"

# ---- Helpers ----
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ---- Check root ----
if [ "$(id -u)" -ne 0 ]; then
    log_error "This script must be run as root (sudo)."
    exit 1
fi

echo ""
echo "============================================"
echo "  K4GSR BL10 Production Server Setup"
echo "============================================"
echo "  Host:     $(hostname)"
echo "  OS:       $(lsb_release -ds 2>/dev/null || grep PRETTY_NAME /etc/os-release | cut -d= -f2)"
echo "  Config:   $CONFIG_FILE"
echo "  Install:  $INSTALL_DIR"
echo "  User:     $SERVICE_USER"
echo "  Python:   $PYTHON_VERSION"
echo "============================================"
echo ""

# -----------------------------------------------------------
# 1. System packages
# -----------------------------------------------------------
log_info "[1/7] Installing system packages..."

apt-get update -qq

if ! command -v "$PY_CMD" &>/dev/null; then
    apt-get install -y software-properties-common
    add-apt-repository -y ppa:deadsnakes/ppa
    apt-get update -qq
    apt-get install -y "${PY_CMD}" "${PY_CMD}-venv" "${PY_CMD}-dev"
    log_info "Python $PYTHON_VERSION installed."
else
    log_info "Python $PYTHON_VERSION already installed: $($PY_CMD --version)"
fi

apt-get install -y git curl wget build-essential net-tools
log_info "System packages ready."

# -----------------------------------------------------------
# 2. Service user
# -----------------------------------------------------------
log_info "[2/7] Creating service user '$SERVICE_USER'..."

if id "$SERVICE_USER" &>/dev/null; then
    log_info "User '$SERVICE_USER' already exists."
else
    useradd --system --create-home --shell /bin/bash "$SERVICE_USER"
    log_info "User '$SERVICE_USER' created."
fi

# -----------------------------------------------------------
# 3. Clone repository
# -----------------------------------------------------------
log_info "[3/7] Setting up repository at $INSTALL_DIR..."

if [ -d "$INSTALL_DIR/.git" ]; then
    log_info "Repository already exists. Pulling latest..."
    cd "$INSTALL_DIR"
    sudo -u "$SERVICE_USER" git fetch origin
    sudo -u "$SERVICE_USER" git checkout "$GITHUB_BRANCH"
    sudo -u "$SERVICE_USER" git pull origin "$GITHUB_BRANCH"
else
    mkdir -p "$(dirname "$INSTALL_DIR")"
    git clone --branch "$GITHUB_BRANCH" "$GITHUB_REPO" "$INSTALL_DIR"
    chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
    log_info "Repository cloned."
fi

cd "$INSTALL_DIR"

# -----------------------------------------------------------
# 4. Python virtual environment
# -----------------------------------------------------------
log_info "[4/7] Setting up Python virtual environment..."

if [ ! -d "$VENV_DIR" ]; then
    sudo -u "$SERVICE_USER" "$PY_CMD" -m venv "$VENV_DIR"
    log_info "Virtual environment created."
else
    log_info "Virtual environment already exists."
fi

sudo -u "$SERVICE_USER" "$VENV_DIR/bin/pip" install --upgrade pip -q
sudo -u "$SERVICE_USER" "$VENV_DIR/bin/pip" install -r server/requirements.txt -q
sudo -u "$SERVICE_USER" "$VENV_DIR/bin/pip" install -r server/requirements_sim.txt -q 2>/dev/null || log_warn "Some simulation packages failed (non-critical)"
log_info "Python dependencies installed."

# -----------------------------------------------------------
# 5. Production .env
# -----------------------------------------------------------
log_info "[5/7] Configuring server .env..."

ENV_FILE="$INSTALL_DIR/server/.env"

if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << ENVEOF
# K4GSR BL10 Production Environment
# Generated by setup_production.sh on $(date -Iseconds)

# NLP Engine
NLP_ENGINE=vllm
VLLM_BASE_URL=http://${VLLM_HOST}:${VLLM_PORT}/v1

# Fallback: Groq cloud API
# NLP_ENGINE=groq
GROQ_API_KEY=your-groq-api-key-here
GROQ_MODEL=llama-3.3-70b-versatile

# Ollama (local, optional)
OLLAMA_URL=http://localhost:11434
OLLAMA_MODEL=qwen3:30b-a3b
ENVEOF

    chown "$SERVICE_USER:$SERVICE_USER" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    log_info ".env created (mode 600). Edit API keys as needed."
else
    log_info ".env already exists. Skipping."
fi

# -----------------------------------------------------------
# 6. Log directory + systemd services
# -----------------------------------------------------------
log_info "[6/7] Installing systemd services..."

mkdir -p "$LOG_DIR"
chown "$SERVICE_USER:$SERVICE_USER" "$LOG_DIR"

SYSTEMD_SRC="$INSTALL_DIR/deploy/systemd"

for svc_file in "$SYSTEMD_SRC"/*.service; do
    [ -f "$svc_file" ] || continue
    svc_name="$(basename "$svc_file")"

    # Substitute config variables into service template
    sed \
        -e "s|__INSTALL_DIR__|${INSTALL_DIR}|g" \
        -e "s|__SERVICE_USER__|${SERVICE_USER}|g" \
        -e "s|__LOG_DIR__|${LOG_DIR}|g" \
        -e "s|__VENV_DIR__|${VENV_DIR}|g" \
        -e "s|__PORT_SERVER__|${PORT_SERVER}|g" \
        -e "s|__PORT_EPICS_CA__|${PORT_EPICS_CA}|g" \
        -e "s|__EPICS_IOC_ADDR_LIST__|${EPICS_IOC_ADDR_LIST}|g" \
        -e "s|__SERVER_MODE__|${SERVER_MODE}|g" \
        "$svc_file" > "/etc/systemd/system/$svc_name"

    log_info "  Installed $svc_name"
done

systemctl daemon-reload
systemctl enable k4gsr-ioc.service 2>/dev/null || true
systemctl enable k4gsr-server.service 2>/dev/null || true
log_info "Services enabled (not started yet)."

# -----------------------------------------------------------
# 7. Firewall
# -----------------------------------------------------------
log_info "[7/7] Configuring firewall..."

if command -v ufw &>/dev/null; then
    ufw allow "${PORT_SERVER}/tcp" comment "K4GSR WebSocket" 2>/dev/null || true
    ufw allow "${PORT_SIMULATION}/tcp" comment "K4GSR Simulation" 2>/dev/null || true
    ufw allow "${PORT_EPICS_CA}/tcp" comment "EPICS CA TCP" 2>/dev/null || true
    ufw allow "${PORT_EPICS_CA}/udp" comment "EPICS CA UDP" 2>/dev/null || true
    ufw allow "${PORT_EPICS_REPEATER}/tcp" comment "EPICS Repeater TCP" 2>/dev/null || true
    ufw allow "${PORT_EPICS_REPEATER}/udp" comment "EPICS Repeater UDP" 2>/dev/null || true
    log_info "Firewall rules added."
else
    log_warn "ufw not found. Open ports manually: ${PORT_SERVER}, ${PORT_SIMULATION}, ${PORT_EPICS_CA}"
fi

# -----------------------------------------------------------
# Summary
# -----------------------------------------------------------
echo ""
echo "============================================"
echo "  Setup Complete"
echo "============================================"
echo ""
echo "  Install:  $INSTALL_DIR"
echo "  User:     $SERVICE_USER"
echo "  Python:   $VENV_DIR/bin/python"
echo "  .env:     $ENV_FILE"
echo "  Logs:     $LOG_DIR/"
echo "  Config:   $CONFIG_FILE"
echo ""
echo "  Quick start:"
echo "    bash $INSTALL_DIR/deploy/beamline_ctl.sh start"
echo "    bash $INSTALL_DIR/deploy/beamline_ctl.sh status"
echo "    bash $INSTALL_DIR/deploy/beamline_ctl.sh logs"
echo ""
echo "  Code updates:"
echo "    bash $INSTALL_DIR/deploy/deploy.sh"
echo "============================================"
