#!/usr/bin/env python3
"""Auto-generate EPICS .db files from pv_store.py PV definitions.

Reads PV definitions (name, value, limits, unit, speed) from pv_store.py
and generates standard EPICS database (.db) files:
  - bl10_motors.db  — ao (setpoint) + ai (readback) for each motor axis
  - bl10_status.db  — ai records for ring/BPM/IC status PVs
  - bl10_all.db     — combined include file

Usage:
    python generate_db.py              # Generate .db files in server/epics/
    python generate_db.py --stdout     # Print combined output to stdout
    python generate_db.py --summary    # Print PV count summary only
"""

import sys
import os
import argparse
from pathlib import Path
from datetime import datetime

# Add server/ to path so we can import pv_store
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from pv_store import PVStore


# ═══════════════════════════════════════════════════════════════════════
# Unit → EPICS field mapping
# ═══════════════════════════════════════════════════════════════════════

# PREC: number of decimal digits for display
UNIT_TO_PREC = {
    'mm':     4,
    'mrad':   4,
    'urad':   2,
    'um':     2,
    'deg':    5,
    'arcsec': 2,
    'Nm':     2,
    '':       3,
}

# EGU: Engineering Units string for EPICS
UNIT_TO_EGU = {
    'mm':     'mm',
    'mrad':   'mrad',
    'urad':   'urad',
    'um':     'um',
    'deg':    'deg',
    'arcsec': 'arcsec',
    'Nm':     'N*m',
    '':       '',
}

# DESC: Human-readable descriptions for key PVs
PV_DESCRIPTIONS = {
    # Ring
    'BL10:RING:Current':  'Storage Ring Current',
    'BL10:RING:Energy':   'Ring Energy',
    'BL10:RING:Lifetime': 'Beam Lifetime',
    'BL10:FE:Shutter':    'Front-End Shutter Status',
    # BPM
    'BL10:XBPM1:X': 'XBPM1 Horizontal Position',
    'BL10:XBPM1:Y': 'XBPM1 Vertical Position',
    'BL10:XBPM2:X': 'XBPM2 Horizontal Position',
    'BL10:XBPM2:Y': 'XBPM2 Vertical Position',
    'BL10:IC1:Current': 'Ion Chamber 1 Current',
}


def prec_for_unit(unit: str) -> int:
    """Get PREC field value from unit string."""
    return UNIT_TO_PREC.get(unit, 3)


def egu_for_unit(unit: str) -> str:
    """Get EGU field value from unit string."""
    return UNIT_TO_EGU.get(unit, unit)


def desc_for_pv(pv_name: str) -> str:
    """Generate a description for a PV."""
    if pv_name in PV_DESCRIPTIONS:
        return PV_DESCRIPTIONS[pv_name]
    # Auto-generate from PV name: "BL10:M1:Pitch" → "M1 Pitch"
    parts = pv_name.split(':')
    if len(parts) >= 3:
        return f'{parts[1]} {parts[2]}'
    return pv_name


def format_record(rtype: str, name: str, fields: list) -> str:
    """Format a single EPICS record definition."""
    lines = [f'record({rtype}, "{name}") {{']
    for fname, fval in fields:
        # Format value: strings in quotes, numbers as-is
        if isinstance(fval, (int, float)):
            lines.append(f'    field({fname}, "{fval}")')
        else:
            lines.append(f'    field({fname}, "{fval}")')
    lines.append('}')
    return '\n'.join(lines)


def generate_records():
    """Generate all EPICS record definitions from PVStore."""
    store = PVStore()
    motor_records = []
    status_records = []

    for pv_name, pv in sorted(store.pvs.items()):
        prec = prec_for_unit(pv.unit)
        egu = egu_for_unit(pv.unit)
        desc = desc_for_pv(pv_name)

        if pv.speed > 0:
            # ── Motor PV: ao (setpoint) + ai (readback) ──
            motor_records.append(format_record('ao', pv_name, [
                ('DESC', f'{desc} Setpoint'),
                ('EGU',  egu),
                ('PREC', prec),
                ('VAL',  pv.value),
                ('DRVH', pv.hi_limit),
                ('DRVL', pv.lo_limit),
                ('HOPR', pv.hi_limit),
                ('LOPR', pv.lo_limit),
            ]))
            motor_records.append(format_record('ai', pv_name + ':RBV', [
                ('DESC', f'{desc} Readback'),
                ('EGU',  egu),
                ('PREC', prec),
                ('VAL',  pv.value),
                ('HOPR', pv.hi_limit),
                ('LOPR', pv.lo_limit),
            ]))
        else:
            # ── Read-only status PV: ai ──
            status_records.append(format_record('ai', pv_name, [
                ('DESC', desc),
                ('EGU',  egu),
                ('PREC', prec),
                ('VAL',  pv.value),
            ]))

    return motor_records, status_records


def write_db_file(path: Path, title: str, records: list):
    """Write records to a .db file with header."""
    n = len(records)
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('#\n')
        f.write(f'# {title}\n')
        f.write(f'# Auto-generated by generate_db.py — {timestamp}\n')
        f.write(f'# {n} records\n')
        f.write('#\n')
        f.write('# DO NOT EDIT — regenerate with: python generate_db.py\n')
        f.write('#\n\n')
        f.write('\n\n'.join(records))
        f.write('\n')
    return n


def main():
    parser = argparse.ArgumentParser(
        description='Generate EPICS .db files from pv_store.py'
    )
    parser.add_argument('--stdout', action='store_true',
                        help='Print combined output to stdout')
    parser.add_argument('--summary', action='store_true',
                        help='Print PV count summary only')
    parser.add_argument('--outdir', type=str, default=None,
                        help='Output directory (default: same as this script)')
    args = parser.parse_args()

    motor_records, status_records = generate_records()
    n_motors = len(motor_records)
    n_status = len(status_records)
    n_total = n_motors + n_status
    # Count unique PVs (motor has 2 records each: setpoint + RBV)
    n_motor_pvs = n_motors // 2

    if args.summary:
        print(f'Motor PVs:    {n_motor_pvs} axes × 2 (setpoint + RBV) = {n_motors} records')
        print(f'Status PVs:   {n_status} records')
        print(f'Total:        {n_total} records')
        return

    if args.stdout:
        all_records = motor_records + status_records
        print('\n\n'.join(all_records))
        return

    # Write to files
    out_dir = Path(args.outdir) if args.outdir else Path(__file__).resolve().parent

    n1 = write_db_file(
        out_dir / 'bl10_motors.db',
        'K4GSR BL10 NanoProbe — Motor PVs (ao setpoint + ai readback)',
        motor_records
    )
    print(f'  bl10_motors.db : {n1} records ({n_motor_pvs} motor axes)')

    n2 = write_db_file(
        out_dir / 'bl10_status.db',
        'K4GSR BL10 NanoProbe — Status PVs (ring, BPM, IC)',
        status_records
    )
    print(f'  bl10_status.db : {n2} records')

    # Combined include file
    all_path = out_dir / 'bl10_all.db'
    with open(all_path, 'w', encoding='utf-8') as f:
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        f.write('#\n')
        f.write('# K4GSR BL10 NanoProbe — All PVs (combined)\n')
        f.write(f'# Auto-generated by generate_db.py — {timestamp}\n')
        f.write(f'# Total: {n_total} records\n')
        f.write('#\n\n')
        f.write('\n\n'.join(motor_records + status_records))
        f.write('\n')
    print(f'  bl10_all.db    : {n_total} records (combined)')
    print(f'\nDone. {n_total} EPICS records generated.')


if __name__ == '__main__':
    main()
