#!/usr/bin/env python3
"""
Generate ion-chamber gas attenuation tables for the JS engine (Phase 1 / A3).

Dumps material_mu(gas, E, kind) [linear attenuation coefficient, 1/cm, at the
xraydb materials-DB default density ~ 1 atm] for N2/He/Ar/air x
photo/incoh/total over 5-25 keV (step 0.1 keV) into a JS table file with a
log-log linear interpolation helper (the Elam tables behind material_mu are
themselves log-log splines, so log-log linear on a 0.1 keV grid is accurate
to <<1% between nodes).

Ground truth program: xraydb (same library as paper/validation/
run_ionchamber_reference.py). Style follows Scripts/generate_optconst.py.

Usage:
    python Scripts/generate_gas_mu.py

Output:
    js/optics/00_gasmu_tables.js
"""
import math
import os
import sys

try:
    import xraydb
    from xraydb.materials import material_mu, get_material
except ImportError:
    print("ERROR: xraydb not found (pip install xraydb).")
    sys.exit(1)

# Energy range: 5-25 keV in 0.1 keV steps (engine operating range)
E_MIN_KEV = 5.0
E_MAX_KEV = 25.0
E_STEP_KEV = 0.1
N_PTS = int(round((E_MAX_KEV - E_MIN_KEV) / E_STEP_KEV)) + 1

# label -> xraydb materials-DB name (ionchamber_fluxes maps N2->nitrogen)
GASES = [
    ('N2', 'nitrogen'),
    ('He', 'helium'),
    ('Ar', 'argon'),
    ('air', 'air'),
]
KINDS = ['photo', 'incoh', 'total']


def compute_tables():
    energies = [E_MIN_KEV + E_STEP_KEV * i for i in range(N_PTS)]
    tables = {}
    densities = {}
    for label, xname in GASES:
        _formula, density = get_material(xname)
        densities[label] = density
        tables[label] = {}
        for kind in KINDS:
            mu = [material_mu(xname, energy=e * 1000.0, kind=kind)
                  for e in energies]
            tables[label][kind] = mu
        print('  %-3s rho=%g g/cm3  mu_total(10keV)=%.4e 1/cm' %
              (label, density, tables[label]['total'][int(round((10.0 - E_MIN_KEV) / E_STEP_KEV))]))
    return energies, tables, densities


def verify_tables(tables):
    """Spot-check log-log interpolation (emulating the JS helper) at
    off-grid energies against direct material_mu calls."""
    test_energies = [5.23, 7.77, 10.05, 12.34, 17.49, 24.91]
    print('\n--- Verification (log-log interp vs direct material_mu) ---')
    worst = 0.0
    for label, xname in GASES:
        for kind in KINDS:
            arr = tables[label][kind]
            for e in test_energies:
                idx = (e - E_MIN_KEV) / E_STEP_KEV
                i = int(idx)
                if i >= N_PTS - 1:
                    i = N_PTS - 2
                e0 = E_MIN_KEV + E_STEP_KEV * i
                e1 = e0 + E_STEP_KEV
                t = (math.log(e) - math.log(e0)) / (math.log(e1) - math.log(e0))
                mu_tbl = math.exp(math.log(arr[i]) * (1 - t) +
                                  math.log(arr[i + 1]) * t)
                mu_ref = material_mu(xname, energy=e * 1000.0, kind=kind)
                err = abs(mu_tbl / mu_ref - 1.0)
                worst = max(worst, err)
    print('  worst off-grid interp error: %.3e (must be << 1e-2)' % worst)
    assert worst < 1e-3, 'interpolation grid too coarse'


def write_js(tables, densities, outpath):
    def fmt_array(arr):
        return '[' + ','.join('%.7e' % v for v in arr) + ']'

    lines = [
        "'use strict';",
        "// ===== optics/00_gasmu_tables.js - ion-chamber gas attenuation tables =====",
        "// Auto-generated by Scripts/generate_gas_mu.py using xraydb %s (Elam tables)" % xraydb.__version__,
        "// DO NOT EDIT MANUALLY",
        "// mu = linear attenuation coefficient [1/cm] at the xraydb materials-DB",
        "// default densities (approx 1 atm): %s g/cm3" %
        ', '.join('%s=%g' % (lab, densities[lab]) for lab, _ in GASES),
        "// Energy grid: %g-%g keV, step %g keV (uniform), N=%d" %
        (E_MIN_KEV, E_MAX_KEV, E_STEP_KEV, N_PTS),
        "// Kinds: photo (photoelectric), incoh (incoherent/Compton),",
        "//        total (photo + coherent + incoherent)",
        "// Interpolation: log-log linear (gasMuInterp below); the Elam tables are",
        "// log-log splines, so this reproduces material_mu to <0.1% between nodes.",
        "",
        "var GASMU_TABLES = {",
        "  E_min_keV: %g," % E_MIN_KEV,
        "  E_step_keV: %g," % E_STEP_KEV,
        "  N: %d," % N_PTS,
        "  density_g_cm3: { %s }," %
        ', '.join('%s: %g' % (lab, densities[lab]) for lab, _ in GASES),
    ]
    for label, _xname in GASES:
        lines.append('  %s: {' % label)
        for k, kind in enumerate(KINDS):
            comma = ',' if k < len(KINDS) - 1 else ''
            lines.append('    %s: %s%s' % (kind, fmt_array(tables[label][kind]), comma))
        lines.append('  },')
    lines.append('};')
    lines.append('')
    lines.append('// Log-log linear interpolation of mu [1/cm] on the uniform energy grid.')
    lines.append('// gas: "N2" | "He" | "Ar" | "air"; kind: "photo" | "incoh" | "total".')
    lines.append('// E_keV outside 5-25 keV is clamped to the table edge.')
    lines.append('function gasMuInterp(gas, E_keV, kind) {')
    lines.append('  var tbl = GASMU_TABLES[gas];')
    lines.append('  if (!tbl || !tbl[kind]) return NaN;')
    lines.append('  var arr = tbl[kind];')
    lines.append('  var n = GASMU_TABLES.N, e0 = GASMU_TABLES.E_min_keV, de = GASMU_TABLES.E_step_keV;')
    lines.append('  var e = E_keV;')
    lines.append('  if (!(e > 0)) return NaN;')
    lines.append('  var eMax = e0 + de * (n - 1);')
    lines.append('  if (e < e0) e = e0;')
    lines.append('  if (e > eMax) e = eMax;')
    lines.append('  var idx = (e - e0) / de;')
    lines.append('  var i = Math.floor(idx);')
    lines.append('  if (i >= n - 1) i = n - 2;')
    lines.append('  var ea = e0 + de * i, eb = ea + de;')
    lines.append('  var t = (Math.log(e) - Math.log(ea)) / (Math.log(eb) - Math.log(ea));')
    lines.append('  if (t < 0) t = 0;')
    lines.append('  if (t > 1) t = 1;')
    lines.append('  return Math.exp(Math.log(arr[i]) * (1 - t) + Math.log(arr[i + 1]) * t);')
    lines.append('}')
    lines.append('')
    lines.append('// ESM bridge: expose module-scoped vars to globalThis')
    lines.append('if(typeof GASMU_TABLES!=="undefined")globalThis.GASMU_TABLES=GASMU_TABLES;')
    lines.append('if(typeof gasMuInterp!=="undefined")globalThis.gasMuInterp=gasMuInterp;')
    lines.append('')

    content = '\n'.join(lines)
    with open(outpath, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)
    print('\nWritten: %s (%.1f KB)' % (outpath, len(content) / 1024.0))


def main():
    outdir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                          'js', 'optics')
    outpath = os.path.join(outdir, '00_gasmu_tables.js')
    print('Generating gas mu tables (%d points, %g-%g keV, xraydb %s)...' %
          (N_PTS, E_MIN_KEV, E_MAX_KEV, xraydb.__version__))
    _energies, tables, densities = compute_tables()
    verify_tables(tables)
    write_js(tables, densities, outpath)
    print('Done.')


if __name__ == '__main__':
    main()
