#!/usr/bin/env python3
"""
Generate optical constant lookup tables for the MC ray tracer.

Uses xraylib to compute ZF1 = 2*delta, ZF2 = 2*beta for Rh, Pt, Si
at 10 eV steps from 3-30 keV.  Output is a JS file containing the tables.

Usage:
    conda run -n oasys_env python Scripts/generate_optconst.py

Output:
    js/optics/00_optconst_tables.js
"""
import sys
import os
import json
import numpy as np

try:
    import xraylib
except ImportError:
    print("ERROR: xraylib not found. Run in oasys_env conda environment.")
    sys.exit(1)

# Energy range: 3-30 keV in 10 eV steps
E_MIN_KEV = 3.0
E_MAX_KEV = 30.0
E_STEP_KEV = 0.01  # 10 eV
N_PTS = int(round((E_MAX_KEV - E_MIN_KEV) / E_STEP_KEV)) + 1

# Materials for the beamline
MATERIALS = {
    'Rh': {'Z': 45, 'descriptor': 'Rh', 'density': 12.41},
    'Pt': {'Z': 78, 'descriptor': 'Pt', 'density': 21.45},
    'Si': {'Z': 14, 'descriptor': 'Si', 'density': 2.33},
}

def compute_tables():
    """Compute ZF1 and ZF2 arrays for each material."""
    energies = np.linspace(E_MIN_KEV, E_MAX_KEV, N_PTS)
    tables = {}

    for name, mat in MATERIALS.items():
        zf1 = np.zeros(N_PTS)
        zf2 = np.zeros(N_PTS)

        for i, E in enumerate(energies):
            try:
                n = xraylib.Refractive_Index(mat['descriptor'], E, mat['density'])
                delta = 1.0 - n.real
                beta = n.imag
                zf1[i] = 2.0 * delta
                zf2[i] = 2.0 * beta
            except Exception as ex:
                # Near absorption edges xraylib may have issues
                print(f"  WARNING: {name} at {E:.3f} keV: {ex}")
                if i > 0:
                    zf1[i] = zf1[i-1]
                    zf2[i] = zf2[i-1]

        tables[name] = {
            'ZF1': zf1.tolist(),
            'ZF2': zf2.tolist(),
        }
        print(f"  {name}: {N_PTS} points, delta range [{zf1.min()/2:.2e}, {zf1.max()/2:.2e}], "
              f"beta range [{zf2.min()/2:.2e}, {zf2.max()/2:.2e}]")

    return energies, tables


def verify_tables(energies, tables):
    """Spot-check a few values against xraylib."""
    test_energies = [5.0, 10.0, 15.0, 20.0, 25.0]
    print("\n--- Verification ---")
    print(f"{'Mat':>4s} {'E(keV)':>8s} {'delta_tbl':>12s} {'delta_ref':>12s} {'err%':>8s}  "
          f"{'beta_tbl':>12s} {'beta_ref':>12s} {'err%':>8s}")

    for name, mat in MATERIALS.items():
        tbl = tables[name]
        for E in test_energies:
            idx = (E - E_MIN_KEV) / E_STEP_KEV
            i = int(idx)
            frac = idx - i
            if i >= N_PTS - 1:
                i = N_PTS - 2
                frac = 1.0

            delta_tbl = (tbl['ZF1'][i] * (1 - frac) + tbl['ZF1'][i+1] * frac) / 2
            beta_tbl = (tbl['ZF2'][i] * (1 - frac) + tbl['ZF2'][i+1] * frac) / 2

            n_ref = xraylib.Refractive_Index(mat['descriptor'], E, mat['density'])
            delta_ref = 1.0 - n_ref.real
            beta_ref = n_ref.imag

            err_d = abs(delta_tbl - delta_ref) / max(abs(delta_ref), 1e-30) * 100
            err_b = abs(beta_tbl - beta_ref) / max(abs(beta_ref), 1e-30) * 100

            print(f"{name:>4s} {E:>8.1f} {delta_tbl:>12.4e} {delta_ref:>12.4e} {err_d:>7.3f}%  "
                  f"{beta_tbl:>12.4e} {beta_ref:>12.4e} {err_b:>7.3f}%")


def write_js(energies, tables, outpath):
    """Write JS file with embedded lookup tables."""

    # Convert to compact JSON (6 significant digits)
    def fmt_array(arr):
        """Format float array compactly."""
        parts = []
        for v in arr:
            if abs(v) < 1e-15:
                parts.append('0')
            else:
                parts.append(f'{v:.6e}')
        return '[' + ','.join(parts) + ']'

    lines = [
        "'use strict';",
        "// ===== optics/00_optconst_tables.js — DABAX-equivalent optical constants =====",
        "// Auto-generated by Scripts/generate_optconst.py using xraylib",
        "// DO NOT EDIT MANUALLY",
        f"// Energy range: {E_MIN_KEV}-{E_MAX_KEV} keV, step={E_STEP_KEV*1000:.0f} eV, N={N_PTS}",
        f"// Materials: {', '.join(MATERIALS.keys())}",
        "// ZF1 = 2*delta, ZF2 = 2*beta (Shadow4 PreRefl convention)",
        "",
        "var OPTCONST_TABLES = {",
        f"  E_min_keV: {E_MIN_KEV},",
        f"  E_step_keV: {E_STEP_KEV},",
        f"  N: {N_PTS},",
    ]

    for name in MATERIALS:
        tbl = tables[name]
        lines.append(f"  {name}: {{")
        lines.append(f"    ZF1: {fmt_array(tbl['ZF1'])},")
        lines.append(f"    ZF2: {fmt_array(tbl['ZF2'])}")
        lines.append("  },")

    lines.append("};")
    lines.append("")

    content = '\n'.join(lines)
    with open(outpath, 'w', encoding='utf-8') as f:
        f.write(content)

    size_kb = len(content) / 1024
    print(f"\nWritten: {outpath} ({size_kb:.1f} KB)")


def main():
    outdir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'js', 'optics')
    outpath = os.path.join(outdir, '00_optconst_tables.js')

    print(f"Generating optical constant tables ({N_PTS} points, {E_MIN_KEV}-{E_MAX_KEV} keV)...")
    energies, tables = compute_tables()
    verify_tables(energies, tables)
    write_js(energies, tables, outpath)
    print("Done.")


if __name__ == '__main__':
    main()
