"""
Generate Si(111) and Si(311) crystal susceptibility tables for JS.
Uses crystalpy/dabax to compute psi_0, psi_H, psi_H_bar (complex)
at every 10 eV from 3-30 keV (same grid as optconst tables).
Output: JS file with lookup tables.
"""
import numpy as np
import os
from crystalpy.diffraction.GeometryType import BraggDiffraction
from crystalpy.diffraction.DiffractionSetupDabax import DiffractionSetupDabax

E_MIN = 3.0   # keV
E_STEP = 0.01 # keV (= 10 eV)
N = 2701      # points -> 3.0 to 30.0 keV

energies_keV = np.array([E_MIN + i * E_STEP for i in range(N)])
energies_eV = energies_keV * 1000.0

crystals = {
    '111': {'h': 1, 'k': 1, 'l': 1},
    '311': {'h': 3, 'k': 1, 'l': 1},
}

out_lines = [
    "'use strict';",
    "// ===== optics/02b_crystal_psi_tables.js -- Si crystal susceptibility tables =====",
    "// Auto-generated by Scripts/generate_crystal_psi.py using crystalpy/dabax",
    "// DO NOT EDIT MANUALLY",
    "// Energy range: %.1f-%.1f keV, step=%g eV, N=%d" % (E_MIN, E_MIN + (N-1)*E_STEP, E_STEP*1000, N),
    "// psi_0, psi_H, psi_H_bar: complex susceptibilities (Zachariasen definition)",
    "// Used by Guigay thick Bragg DCM reflectivity calculation",
    "",
]

for label, hkl in crystals.items():
    print(f"Computing Si({label})...")
    setup = DiffractionSetupDabax(
        geometry_type=BraggDiffraction(),
        crystal_name="Si",
        thickness=0.010,
        miller_h=hkl['h'], miller_k=hkl['k'], miller_l=hkl['l'],
        asymmetry_angle=0.0,
        azimuthal_angle=0.0,
    )

    d_A = setup.dSpacing()
    V_A3 = setup.unitcellVolume()
    print(f"  d-spacing: {d_A:.6f} A, V_cell: {V_A3:.4f} A^3")

    psi0_re = np.zeros(N)
    psi0_im = np.zeros(N)
    psiH_re = np.zeros(N)
    psiH_im = np.zeros(N)
    psiHb_re = np.zeros(N)
    psiHb_im = np.zeros(N)

    for i, E_eV in enumerate(energies_eV):
        p0, pH, pHb = setup.psiAll(E_eV)
        # psiAll returns arrays when energy is scalar, extract scalar
        psi0_re[i] = float(np.real(p0).flat[0])
        psi0_im[i] = float(np.imag(p0).flat[0])
        psiH_re[i] = float(np.real(pH).flat[0])
        psiH_im[i] = float(np.imag(pH).flat[0])
        psiHb_re[i] = float(np.real(pHb).flat[0])
        psiHb_im[i] = float(np.imag(pHb).flat[0])

        if i % 500 == 0:
            print(f"  {i}/{N} ({energies_keV[i]:.1f} keV)")

    # Format arrays
    def fmt_arr(arr):
        parts = []
        for v in arr:
            parts.append("%.6e" % v)
        return ','.join(parts)

    out_lines.append(f"// Si({label}): d={d_A:.6f} A, V={V_A3:.4f} A^3")
    out_lines.append(f"var SI{label}_PSI = {{")
    out_lines.append(f"  d_A: {d_A:.6f},")
    out_lines.append(f"  V_A3: {V_A3:.4f},")
    out_lines.append(f"  psi0_re: [{fmt_arr(psi0_re)}],")
    out_lines.append(f"  psi0_im: [{fmt_arr(psi0_im)}],")
    out_lines.append(f"  psiH_re: [{fmt_arr(psiH_re)}],")
    out_lines.append(f"  psiH_im: [{fmt_arr(psiH_im)}],")
    out_lines.append(f"  psiHb_re: [{fmt_arr(psiHb_re)}],")
    out_lines.append(f"  psiHb_im: [{fmt_arr(psiHb_im)}],")
    out_lines.append("};")
    out_lines.append("")

    # Verify against S4 reference
    for E_test in [5000, 10000, 20000]:
        idx = int((E_test/1000 - E_MIN) / E_STEP + 0.5)
        p0, pH, pHb = setup.psiAll(float(E_test))
        print(f"  Verify {E_test} eV:")
        print(f"    psi_0 = {float(np.real(p0).flat[0]):.6e} + {float(np.imag(p0).flat[0]):.6e}j")
        print(f"    table = {psi0_re[idx]:.6e} + {psi0_im[idx]:.6e}j")

# Helper function to look up psi values
out_lines.extend([
    "// Lookup function: returns {psi0_re, psi0_im, psiH_re, psiH_im, psiHb_re, psiHb_im}",
    "// E_keV: energy in keV, crystal: '111' or '311'",
    "function crystalPsi(E_keV, crystal) {",
    "  var tbl = (crystal === '311') ? SI311_PSI : SI111_PSI;",
    "  var idx = (E_keV - 3.0) / 0.01;",
    "  var i0 = Math.max(0, Math.min(2699, Math.floor(idx)));",
    "  var i1 = Math.min(2700, i0 + 1);",
    "  var t = idx - i0;",
    "  if (t < 0) t = 0; if (t > 1) t = 1;",
    "  return {",
    "    psi0_re: tbl.psi0_re[i0] + t * (tbl.psi0_re[i1] - tbl.psi0_re[i0]),",
    "    psi0_im: tbl.psi0_im[i0] + t * (tbl.psi0_im[i1] - tbl.psi0_im[i0]),",
    "    psiH_re: tbl.psiH_re[i0] + t * (tbl.psiH_re[i1] - tbl.psiH_re[i0]),",
    "    psiH_im: tbl.psiH_im[i0] + t * (tbl.psiH_im[i1] - tbl.psiH_im[i0]),",
    "    psiHb_re: tbl.psiHb_re[i0] + t * (tbl.psiHb_re[i1] - tbl.psiHb_re[i0]),",
    "    psiHb_im: tbl.psiHb_im[i0] + t * (tbl.psiHb_im[i1] - tbl.psiHb_im[i0]),",
    "  };",
    "}",
    "",
])

out_path = os.path.join(os.path.dirname(os.path.dirname(__file__)),
                         'js', 'optics', '02b_crystal_psi_tables.js')
with open(out_path, 'w', encoding='ascii') as f:
    f.write('\n'.join(out_lines))
print(f"\nSaved to {out_path}")
print(f"File size: {os.path.getsize(out_path) / 1024:.0f} KB")
