# -*- coding: utf-8 -*-
"""layout_to_xrt.py -- generate a runnable xrt script from a HANBIT layout JSON.

Phase 1 / A2 (hybrid backend): the browser exports the live optical state with
exportBeamlineLayout() (js/optics/08_layout_export.js, schema
'hanbit.beamline.layout' v1); this OFFLINE generator turns that JSON into a
self-contained xrt 1.6.0 geometric ray-trace of the full beamline

    IVU undulator -> WB slit -> M1 (sagittal V-focus toroid)
    -> DCM Si(111)/(311) -> M2 (tangential H-focus elliptical cylinder)
    -> SSA -> KB slit -> KB-V -> KB-H (elliptical cylinders) -> sample screen

Modeling conventions deliberately follow the JSR fig_R1 xrt comparison code
(paper/JSR_Paper_review/figures/fig_R1/build_fig_R1_xrt.py), which the paper
validated against the engine:
  - units mm / eV / rad, raycing.BeamLine, sequential shine/reflect/propagate
  - KB mirrors = EllipticalMirrorParam with the engine p/q arms measured from
    the SSA secondary source (positionRoll selects the focusing plane)
  - per-element local placement on the ACTUAL beam (runtime auto-centering)
xrt pitch/positionRoll sign conventions were verified empirically on
xrt 1.6.0 (see docs/tasks/TASK_A2_XRT_EXPORT.md section 4):
  positionRoll=+pi/2 deflects +x, grazing = pitch - alpha_in
  positionRoll=-pi/2 deflects -x, grazing = pitch + alpha_in
  positionRoll=0     deflects +z, grazing = pitch - alpha_in
(alpha_in = in-plane angle of the incoming beam, atan2(a,b) or atan2(c,b)).

This module only GENERATES text -- xrt is imported by the generated script,
not by this generator (so generation works in any Python).

Usage:
    python Scripts/layout_to_xrt.py <layout.json> <out_script.py>
    python <out_script.py> [--nrays N] [--out results.json]

Known modeling simplifications (kickoff scope, documented in TASK_A2):
  - DCM diffracts in the VERTICAL plane (xrt default, best-tested); the real
    HDCM has a horizontal fixed exit. Direction is restored either way; only
    the 12 mm offset direction differs, which auto-centering absorbs.
  - Fixed masks / attenuators (default 'None') are not modeled.
  - The undulator K is set by xrt's targetE=[E, harmonic]; the engine's
    gap->K calibration is carried in the JSON for reference only.
"""
import io
import json
import os
import sys

SUPPORTED_SCHEMA = 'hanbit.beamline.layout'
SUPPORTED_VERSION = 1

REQUIRED_KEYS = ('schema', 'schemaVersion', 'beam', 'source', 'components',
                 'slits', 'mirrors', 'dcm')


def load_layout(path):
    """Read + validate a layout JSON exported by exportBeamlineLayout()."""
    with io.open(path, 'r', encoding='utf-8') as f:
        layout = json.load(f)
    for k in REQUIRED_KEYS:
        if k not in layout:
            raise ValueError('layout JSON missing key: %r' % k)
    if layout['schema'] != SUPPORTED_SCHEMA:
        raise ValueError('unsupported schema %r (want %r)'
                         % (layout['schema'], SUPPORTED_SCHEMA))
    if int(layout['schemaVersion']) > SUPPORTED_VERSION:
        raise ValueError('layout schemaVersion %s > supported %s'
                         % (layout['schemaVersion'], SUPPORTED_VERSION))
    ids = set(c['id'] for c in layout['components'])
    for need in ('ivu', 'wbslit', 'm1', 'dcm', 'm2', 'ssa', 'kbslit',
                 'kbv', 'kbh', 'sample'):
        if need not in ids:
            raise ValueError('layout components missing id: %r' % need)
    return layout


TEMPLATE = r'''# -*- coding: utf-8 -*-
"""AUTO-GENERATED xrt beamline script -- DO NOT EDIT BY HAND.

Generated by Scripts/layout_to_xrt.py from: @@SRC_NAME@@
Engine version: @@ENGINE_VERSION@@   exported: @@EXPORTED_AT@@
Chain: IVU undulator -> WB slit -> M1 (toroid, sagittal V-focus) -> DCM
       -> M2 (elliptical cylinder, tangential H-focus) -> SSA -> KB slit
       -> KB-V -> KB-H (elliptical cylinders) -> sample screen
Conventions: fig_R1 xrt code (mm/eV/rad, sequential trace, EllipticalMirrorParam
KB with SSA secondary-source p/q arms); see Scripts/layout_to_xrt.py docstring.

Run:  python @@OUT_NAME@@ [--nrays N] [--out results.json]
Requires: xrt 1.6.0, numpy (no OpenCL needed; falls back to numpy).
"""
import json
import sys

import numpy as np

LAYOUT = json.loads(r"""
@@LAYOUT_JSON@@
""")

M = 1.0e3          # m -> mm
DEFAULT_NRAYS = 5000
# Relative half-band sampled around E0. Must cover the DCM acceptance
# (Si111 Darwin ~1.3e-4 + slit-angle dispersion ~1.1e-4) but not be much
# wider, or most rays carry near-zero weight after the DCM reflectivity and
# the effective sample size collapses.
ENERGY_BAND = 1.0e-3


def _good(beam):
    return (beam.state == 1) & np.isfinite(beam.x) & ((beam.Jss + beam.Jpp) > 0)


def _centroid(beam):
    """Intensity-weighted beam centroid position [mm], unit direction, n good."""
    g = _good(beam)
    n = int(g.sum())
    if n == 0:
        raise RuntimeError('beam lost: no good rays at this stage')
    w = (beam.Jss + beam.Jpp)[g]
    W = w.sum()
    p = np.array([(beam.x[g] * w).sum(), (beam.y[g] * w).sum(),
                  (beam.z[g] * w).sum()]) / W
    d = np.array([(beam.a[g] * w).sum(), (beam.b[g] * w).sum(),
                  (beam.c[g] * w).sum()]) / W
    d /= np.linalg.norm(d)
    return p, d, n


def _fwhm(x, y):
    """Half-max crossing FWHM with linear interpolation (fig_R1 convention)."""
    y = np.asarray(y, float)
    if y.max() <= 0:
        return float('nan')
    ip = int(np.argmax(y)); h = y[ip] / 2.0
    iL = ip
    while iL > 0 and y[iL] >= h:
        iL -= 1
    xl = x[iL] + (h - y[iL]) * (x[iL + 1] - x[iL]) / (y[iL + 1] - y[iL]) \
        if y[iL] < h else x[iL]
    iR = ip
    while iR < len(y) - 1 and y[iR] >= h:
        iR += 1
    xr = x[iR - 1] + (h - y[iR - 1]) * (x[iR] - x[iR - 1]) / (y[iR] - y[iR - 1]) \
        if y[iR] < h else x[iR]
    return abs(xr - xl)


def _wpercentile(v, w, q):
    """Weighted percentile (q in 0..100) of values v with weights w."""
    o = np.argsort(v)
    cw = np.cumsum(w[o])
    return np.interp(q / 100.0 * cw[-1], cw, v[o])


def _weighted_fwhm(v_mm, w, nspan=4.0):
    """FWHM [mm] of a weighted 1D distribution via binned marginal.
    The histogram window comes from weighted percentiles (robust against the
    sparse halo of mirror-edge aberration / DCM band tails) and the bin count
    adapts to the EFFECTIVE sample size (undulator+DCM weights are heavily
    skewed), so the marginal is neither under- nor over-resolved.
    Returns (fwhm, weighted median, core rms within the window)."""
    c = _wpercentile(v_mm, w, 50.0)
    span = _wpercentile(v_mm, w, 90.0) - _wpercentile(v_mm, w, 10.0)
    if not np.isfinite(span) or span <= 0:
        return float('nan'), c, float('nan')
    half = nspan * span
    sel = np.abs(v_mm - c) < half
    ws = w[sel]
    effN = ws.sum() ** 2 / (ws ** 2).sum()
    nbins = int(max(15, min(401, 4.0 * np.sqrt(effN))))
    edges = np.linspace(c - half, c + half, nbins + 1)
    hist, _ = np.histogram(v_mm[sel], bins=edges, weights=ws)
    centers = 0.5 * (edges[:-1] + edges[1:])
    cc = (v_mm[sel] * ws).sum() / ws.sum()
    sig = np.sqrt(((v_mm[sel] - cc) ** 2 * ws).sum() / ws.sum())
    return _fwhm(centers, hist), c, sig


def main(nrays=DEFAULT_NRAYS, out_json=None):
    import xrt.backends.raycing as raycing
    import xrt.backends.raycing.apertures as rapts
    import xrt.backends.raycing.materials as rm
    import xrt.backends.raycing.oes as roes
    import xrt.backends.raycing.screens as rscreens
    import xrt.backends.raycing.sources as rsources

    L = LAYOUT
    posm = dict((c['id'], c['position_m']) for c in L['components'])
    beamL, srcL, slitL, mirL = L['beam'], L['source'], L['slits'], L['mirrors']
    E0 = beamL['energy_keV'] * 1e3          # eV
    harm = int(round(beamL['harmonic']))

    # --- materials (engine MIRROR_STRIPES densities, g/cm^3) ---
    coatings = {
        'Pt': rm.Material('Pt', rho=21.45, kind='mirror'),
        'Rh': rm.Material('Rh', rho=12.41, kind='mirror'),
        'Si': rm.Material('Si', rho=2.33, kind='mirror'),
    }
    def coat(name):
        return coatings.get(name.replace('(substrate)', ''), coatings['Pt'])
    hkl = (3, 1, 1) if L['dcm']['crystal'] == '311' else (1, 1, 1)
    crystal = rm.CrystalSi(hkl=hkl)

    bl = raycing.BeamLine(azimuth=0.0, height=0.0)

    # --- undulator source (engine live electron-beam params) ---
    # acceptance: overfill the WB slit (engine convention: slit defines it)
    s_wb = posm['wbslit']
    xpm = 1.2 * (slitL['wb']['hGap_mm'] / 2.0 + abs(slitL['wb']['hCenter_mm'])) \
        / (s_wb * M) * 1e3   # mrad
    zpm = 1.2 * (slitL['wb']['vGap_mm'] / 2.0 + abs(slitL['wb']['vCenter_mm'])) \
        / (s_wb * M) * 1e3
    und = rsources.Undulator(
        bl=bl, name='IVU24', center=(0, 0, 0), nrays=nrays,
        eE=srcL['E_GeV'], eI=srcL['I_mA'] / 1e3, eEspread=srcL['eSpread'],
        eEpsilonX=srcL['emitX_m_rad'] * 1e9,   # nm rad
        eEpsilonZ=srcL['emitY_m_rad'] * 1e9,
        betaX=srcL['betaX_m'], betaZ=srcL['betaY_m'],
        period=srcL['lambdaU_mm'], n=int(srcL['nPeriods']),
        targetE=[E0, harm],
        eMin=E0 * (1 - ENERGY_BAND), eMax=E0 * (1 + ENERGY_BAND),
        distE='eV', xPrimeMax=xpm, zPrimeMax=zpm,
        uniformRayDensity=True)
    print('undulator: E0=%.1f eV harmonic n=%d K=%.4f  acceptance %.4f x %.4f mrad'
          % (E0, harm, und.K, xpm, zpm))
    print('shining %d rays ...' % nrays)
    beam = und.shine()
    # persistent alive mask: xrt's reflect()/propagate() re-evaluate beam.state
    # per element, RESURRECTING rays lost at an earlier element (verified on
    # xrt 1.6.0: a ray lost at KB-V came back state=1 after KB-H). Ray order is
    # preserved through the chain, so an accumulated mask is exact.
    alive = (beam.state == 1)
    stages = [('source', int(alive.sum()))]

    # --- analytic chief-ray bookkeeping ---
    # Statistical (mean-of-rays) centering is biased by the asymmetric mirror
    # footprint (measured: ~13 mm along a 300 mm KB at 3 mrad), which would
    # misplace the downstream foci. The chief ray is exact: it hits each
    # element center and deflects by exactly 2*grazing there.
    p_c = np.zeros(3)               # chief position [mm]
    d_c = np.array([0., 1., 0.])    # chief direction (unit)
    s_cur = 0.0                     # chief path length [m]

    def advance(s_to):
        """Center of the next element on the chief-ray axis [mm]."""
        return tuple(p_c + d_c * (s_to - s_cur) * M)

    def rot_h(d, phi):
        """Rotate direction in the horizontal plane; +phi deflects +x."""
        return np.array([d[0] * np.cos(phi) + d[1] * np.sin(phi),
                         -d[0] * np.sin(phi) + d[1] * np.cos(phi), d[2]])

    def rot_v(d, phi):
        """Rotate direction in the vertical plane; +phi deflects +z."""
        return np.array([d[0], -d[2] * np.sin(phi) + d[1] * np.cos(phi),
                         d[2] * np.cos(phi) + d[1] * np.sin(phi)])

    # --- WB slit ---
    wb = slitL['wb']
    wbAp = rapts.RectangularAperture(
        bl=bl, name='WBslit', center=advance(posm['wbslit']),
        opening=[wb['hCenter_mm'] - wb['hGap_mm'] / 2., wb['hCenter_mm'] + wb['hGap_mm'] / 2.,
                 wb['vCenter_mm'] - wb['vGap_mm'] / 2., wb['vCenter_mm'] + wb['vGap_mm'] / 2.])
    # needNewGlobal=True: plain propagate() only FLAGS the input beam (rays stay
    # at the previous element); the returned global beam sits AT the aperture.
    beam, _wbloc = wbAp.propagate(beam, needNewGlobal=True)
    p_c = np.array(wbAp.center); s_cur = posm['wbslit']
    alive &= (beam.state == 1)
    stages.append(('wbslit', int(alive.sum())))

    # --- M1: fixed-curvature toroid, sagittal V-focus, horizontal deflect +x ---
    m1 = mirL['m1']
    th1 = m1['pitch_mrad'] * 1e-3
    alpha_h = np.arctan2(d_c[0], d_c[1])
    p1, q1 = m1['p_m'] * M, m1['q_m'] * M
    r_sag = 2.0 * p1 * q1 * np.sin(th1) / (p1 + q1)   # Coddington sagittal [mm]
    m1oe = roes.ToroidMirror(
        bl=bl, name='M1', center=advance(posm['m1']),
        pitch=th1 + alpha_h, positionRoll=np.pi / 2,
        R=1.0e9, r=r_sag, material=coat(m1['coating']),
        limPhysX=[-m1['width_m'] * M / 2, m1['width_m'] * M / 2],
        limPhysY=[-m1['length_m'] * M / 2, m1['length_m'] * M / 2])
    beam, _m1loc = m1oe.reflect(beam)   # xrt returns NEW beams; input unchanged
    p_c = np.array(m1oe.center); d_c = rot_h(d_c, 2 * th1); s_cur = posm['m1']
    alive &= (beam.state == 1)
    stages.append(('M1', int(alive.sum())))

    # --- DCM (vertical diffraction, fixed exit; see header note) ---
    dcm = roes.DCM(
        bl=bl, name='DCM', center=advance(posm['dcm']),
        bragg=[E0], material=crystal, material2=crystal,
        fixedOffset=L['dcm']['fixedExit_mm'],
        limPhysX=[-30, 30], limPhysY=[-60, 60],
        limPhysX2=[-30, 30], limPhysY2=[-60, 60])
    beam, _l1, _l2 = dcm.double_reflect(beam)
    # fixed exit: direction restored, chief displaced by fixedOffset in the
    # (vertical) diffraction plane, perpendicular to the beam
    p_c = np.array(dcm.center) + np.array([0., 0., L['dcm']['fixedExit_mm']])
    s_cur = posm['dcm']
    alive &= (beam.state == 1)
    stages.append(('DCM', int(alive.sum())))

    # --- M2: bendable elliptical cylinder, tangential H-focus, deflect -x ---
    m2 = mirL['m2']
    th2 = m2['pitch_mrad'] * 1e-3
    alpha_h = np.arctan2(d_c[0], d_c[1])
    m2oe = roes.EllipticalMirrorParam(
        bl=bl, name='M2', center=advance(posm['m2']),
        p=m2['p_m'] * M, q=m2['q_m'] * M, pAxis=tuple(d_c),
        pitch=th2 - alpha_h, positionRoll=-np.pi / 2, isCylindrical=True,
        material=coat(m2['coating']),
        limPhysX=[-m2['width_m'] * M / 2, m2['width_m'] * M / 2],
        limPhysY=[-m2['length_m'] * M / 2, m2['length_m'] * M / 2])
    beam, _m2loc = m2oe.reflect(beam)
    p_c = np.array(m2oe.center); d_c = rot_h(d_c, -2 * th2); s_cur = posm['m2']
    alive &= (beam.state == 1)
    stages.append(('M2', int(alive.sum())))

    # --- SSA ---
    ssa = slitL['ssa']
    um = 1e-3   # um -> mm
    ssaAp = rapts.RectangularAperture(
        bl=bl, name='SSA', center=advance(posm['ssa']),
        opening=[(ssa['hCenter_um'] - ssa['hGap_um'] / 2.) * um,
                 (ssa['hCenter_um'] + ssa['hGap_um'] / 2.) * um,
                 (ssa['vCenter_um'] - ssa['vGap_um'] / 2.) * um,
                 (ssa['vCenter_um'] + ssa['vGap_um'] / 2.) * um])
    beam, _ssaloc = ssaAp.propagate(beam, needNewGlobal=True)
    p_c = np.array(ssaAp.center); s_cur = posm['ssa']
    alive &= (beam.state == 1)
    stages.append(('SSA', int(alive.sum())))

    # --- KB slit ---
    kbs = slitL['kbslit']
    kbsAp = rapts.RectangularAperture(
        bl=bl, name='KBslit', center=advance(posm['kbslit']),
        opening=[(kbs['hCenter_um'] - kbs['hGap_um'] / 2.) * um,
                 (kbs['hCenter_um'] + kbs['hGap_um'] / 2.) * um,
                 (kbs['vCenter_um'] - kbs['vGap_um'] / 2.) * um,
                 (kbs['vCenter_um'] + kbs['vGap_um'] / 2.) * um])
    beam, _kbsloc = kbsAp.propagate(beam, needNewGlobal=True)
    p_c = np.array(kbsAp.center); s_cur = posm['kbslit']
    alive &= (beam.state == 1)
    stages.append(('KBslit', int(alive.sum())))

    # --- KB-V: elliptical cylinder, vertical deflect +z ---
    kbv = mirL['kbv']
    thv = kbv['pitch_mrad'] * 1e-3
    alpha_v = np.arctan2(d_c[2], d_c[1])
    kbvoe = roes.EllipticalMirrorParam(
        bl=bl, name='KB-V', center=advance(posm['kbv']),
        p=kbv['p_m'] * M, q=kbv['q_m'] * M, pAxis=tuple(d_c),
        pitch=thv + alpha_v, positionRoll=0.0, isCylindrical=True,
        material=coat(kbv['coating']),
        limPhysX=[-kbv['width_m'] * M / 2, kbv['width_m'] * M / 2],
        limPhysY=[-kbv['length_m'] * M / 2, kbv['length_m'] * M / 2])
    beam, _kbvloc = kbvoe.reflect(beam)
    p_c = np.array(kbvoe.center); d_c = rot_v(d_c, 2 * thv); s_cur = posm['kbv']
    alive &= (beam.state == 1)
    stages.append(('KB-V', int(alive.sum())))

    # --- KB-H: elliptical cylinder, horizontal deflect +x ---
    kbh = mirL['kbh']
    thh = kbh['pitch_mrad'] * 1e-3
    alpha_h = np.arctan2(d_c[0], d_c[1])
    kbhoe = roes.EllipticalMirrorParam(
        bl=bl, name='KB-H', center=advance(posm['kbh']),
        p=kbh['p_m'] * M, q=kbh['q_m'] * M, pAxis=tuple(d_c),
        pitch=thh + alpha_h, positionRoll=np.pi / 2, isCylindrical=True,
        material=coat(kbh['coating']),
        limPhysX=[-kbh['width_m'] * M / 2, kbh['width_m'] * M / 2],
        limPhysY=[-kbh['length_m'] * M / 2, kbh['length_m'] * M / 2])
    beam, _kbhloc = kbhoe.reflect(beam)
    p_c = np.array(kbhoe.center); d_c = rot_h(d_c, 2 * thh); s_cur = posm['kbh']
    alive &= (beam.state == 1)
    stages.append(('KB-H', int(alive.sum())))

    # --- sample screen ---
    scr = rscreens.Screen(bl=bl, name='sample', center=advance(posm['sample']))
    bs = scr.expose(beam)
    g = alive & _good(bs)   # alive: exclude rays resurrected after a loss
    w = (bs.Jss + bs.Jpp)[g]
    stages.append(('sample', int(g.sum())))

    fH, cH, sH = _weighted_fwhm(bs.x[g], w)
    fV, cV, sV = _weighted_fwhm(bs.z[g], w)
    effN = float(w.sum() ** 2 / (w ** 2).sum()) if g.sum() else 0.0

    print('\n=== stage survival (good rays) ===')
    for name, cnt in stages:
        print('  %-8s %d' % (name, cnt))
    print('\n=== sample plane (xrt geometric, %d rays traced) ===' % nrays)
    print('  FWHM (marginal)  H = %.1f nm   V = %.1f nm' % (fH * 1e6, fV * 1e6))
    print('  core RMS         H = %.1f nm   V = %.1f nm' % (sH * 1e6, sV * 1e6))
    print('  FWHM (2.355*rms) H = %.1f nm   V = %.1f nm'
          % (2.355 * sH * 1e6, 2.355 * sV * 1e6))
    print('  weight sum (flux proxy, a.u.) = %.4e' % w.sum())
    print('  effective sample size (sum w)^2/sum w^2 = %.1f' % effN)
    if effN < 50:
        print('  WARNING: low effective sample size; increase --nrays')

    results = {
        'layout_engineVersion': L.get('engineVersion'),
        'energy_keV': beamL['energy_keV'], 'harmonic': harm,
        'crystal': L['dcm']['crystal'], 'K_xrt': float(und.K),
        'nrays': nrays,
        'stages': [{'name': nm, 'goodRays': cnt} for nm, cnt in stages],
        'sample': {
            'fwhmH_nm': fH * 1e6, 'fwhmV_nm': fV * 1e6,
            'fwhmH_gauss_nm': 2.355 * sH * 1e6, 'fwhmV_gauss_nm': 2.355 * sV * 1e6,
            'rmsH_nm': sH * 1e6, 'rmsV_nm': sV * 1e6,
            'centroidH_mm': cH, 'centroidV_mm': cV,
            'weightSum_au': float(w.sum()),
            'effectiveN': effN,
        },
    }
    if out_json:
        with open(out_json, 'w') as f:
            json.dump(results, f, indent=1)
        print('saved: %s' % out_json)
    return results


if __name__ == '__main__':
    nr, oj = DEFAULT_NRAYS, None
    argv = sys.argv[1:]
    if '--nrays' in argv:
        nr = int(argv[argv.index('--nrays') + 1])
    if '--out' in argv:
        oj = argv[argv.index('--out') + 1]
    main(nrays=nr, out_json=oj)
'''


def generate(layout, out_path, src_name='layout.json'):
    """Write the runnable xrt script for *layout* to *out_path*."""
    text = TEMPLATE
    text = text.replace('@@SRC_NAME@@', os.path.basename(src_name))
    text = text.replace('@@OUT_NAME@@', os.path.basename(out_path))
    text = text.replace('@@ENGINE_VERSION@@', str(layout.get('engineVersion')))
    text = text.replace('@@EXPORTED_AT@@', str(layout.get('exportedAt')))
    text = text.replace('@@LAYOUT_JSON@@', json.dumps(layout, indent=1))
    with io.open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    return out_path


def main(argv):
    if len(argv) < 2:
        print('usage: python Scripts/layout_to_xrt.py <layout.json> <out_script.py>')
        return 2
    layout_path, out_path = argv[0], argv[1]
    layout = load_layout(layout_path)
    generate(layout, out_path, src_name=layout_path)
    print('layout  : %s (engine %s, exported %s)'
          % (layout_path, layout.get('engineVersion'), layout.get('exportedAt')))
    print('generated: %s' % out_path)
    print('run      : python %s [--nrays N] [--out results.json]' % out_path)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
